### ISSUE TITLE
When running not in the app folder, the app crashes 

### ISSUE THREAD

**Issue by ThatCopy** [Sv443/PolishCow#2]
When I run the app with just drag and drop to a terminal windows it can't find the files so the app crashes.

**Comment by Sv443** [comment]
Thanks for creating an issue and PR, but could you please add a screenshot or error message?

**Comment by ThatCopy** [comment]
Sure
![Screenshot 2020-11-13 at 13 35 27](https://user-images.githubusercontent.com/62877244/99072856-18c7fd00-25b5-11eb-870c-7e960c29ea24.png)

**Comment by Sv443** [comment]
Quick fix is to cd to the directory where the exe is located. Will definitely implement your PR tho
